name = "app-builder-frontend"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"
VITE_API_BASE_URL = "https://app-builder.socialoauth.workers.dev"
VITE_STRIPE_PUBLISHABLE_KEY = "pk_live_your_publishable_key_here"

# Pages configuration
pages_build_output_dir = "dist"

# Pages deployment configuration
[[pages_build_config]]
# Build command and output
build_command = "npm run build"
destination_dir = "dist"
root_dir = "."

# Environment variables for build time
[build]
command = "npm run build"
cwd = "."

[build.env]
NODE_ENV = "production"
