name: Deploy to Oracle Cloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  DEPLOY_METHOD: kubernetes  # Change to 'functions' for Oracle Functions

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Oracle Cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t oauth-hub:latest .

      - name: Login to Oracle Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.OCI_REGION }}.ocir.io
          username: ${{ secrets.OCI_TENANCY_NAMESPACE }}/${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_AUTH_TOKEN }}

      - name: Push Docker image to OCIR
        run: |
          IMAGE_NAME="${{ secrets.OCI_REGION }}.ocir.io/${{ secrets.OCI_TENANCY_NAMESPACE }}/oauth-hub:latest"
          docker tag oauth-hub:latest $IMAGE_NAME
          docker push $IMAGE_NAME

      - name: Deploy to Oracle Cloud
        run: |
          chmod +x deploy-to-oracle.sh
          ./deploy-to-oracle.sh
        env:
          OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_VCN_ID: ${{ secrets.OCI_VCN_ID }}
          OCI_TENANCY_NAMESPACE: ${{ secrets.OCI_TENANCY_NAMESPACE }}
          OCI_USERNAME: ${{ secrets.OCI_USERNAME }}
          OCI_AUTH_TOKEN: ${{ secrets.OCI_AUTH_TOKEN }}
          DEPLOY_METHOD: ${{ env.DEPLOY_METHOD }}