name: Deploy OAuth Hub to Oracle Cloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run backend tests
      run: npm run test:backend

    - name: Build frontend
      run: npm run build:frontend

    - name: Run frontend tests
      run: cd frontend && npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install OCI CLI
      run: |
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Configure OCI CLI
      run: |
        oci setup config --file ~/.oci/config
        echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem
      env:
        OCI_CLI_CONFIG_FILE: ~/.oci/config

    - name: Deploy to Oracle Cloud
      env:
        ORACLE_REGION: ${{ secrets.ORACLE_REGION }}
        COMPARTMENT_ID: ${{ secrets.COMPARTMENT_ID }}
        SUBNET_ID: ${{ secrets.SUBNET_ID }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        IMAGE_ID: ${{ secrets.IMAGE_ID }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_CONNECT_STRING: ${{ secrets.DB_CONNECT_STRING }}
        APP_PORT: ${{ secrets.APP_PORT }}
        NODE_ENV: production
      run: |
        chmod +x deploy-to-oracle.sh
        ./deploy-to-oracle.sh