name: Deploy to Oracle Cloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Oracle Cloud
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Oracle Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.CRM_SERVER_IP }}
          username: ${{ secrets.CRM_SERVER_USER }}
          key: ${{ secrets.CRM_SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Navigate to app directory
            cd /opt/oauth-hub || mkdir -p /opt/oauth-hub && cd /opt/oauth-hub

            # Pull latest changes
            if [ -d .git ]; then
              git pull origin main
            else
              git clone https://github.com/Jgracier/Oauth-Hub.git .
            fi

            # Install dependencies
            npm install

            # Set environment variables
            export DATABASE_URL="${{ secrets.CRM_DATABASE_URL }}"
            export NODE_ENV=production
            export PORT=3000

            # Restart application with PM2
            if command -v pm2 &> /dev/null; then
              pm2 restart oauth-hub || pm2 start server.js --name oauth-hub
              pm2 save
            else
              # Fallback to direct node if PM2 not available
              pkill -f "node server.js" || true
              nohup node server.js > app.log 2>&1 &
            fi

            echo "✅ OAuth Hub deployed successfully!"